program ramp
!! test of the one vs all time routine on a 2D mesh with two layers
!! of different velocities. The interface between the two layers
!! contains a ramp.
!! The mesh, the velocity field and the theoretical are loaded from
!! a legacy ascii vtke file generated by the python script domain.py  
!! We use the slow option because we expect two diffraction points.

use generic
use lists
use LAT_mesh
use LAT_time
use time
use iomod
implicit none

   type(mesh) :: amesh
   real(pr), dimension(:), allocatable :: traveltime, velocity, theo_time, error_time
   real(pr), dimension(:), allocatable :: branch_id_r
   integer(pin), dimension(:), allocatable :: branch_id
   real(pr) :: start_time, finish_time
   type(diff) :: adiff
   integer(pin) :: i, k
   type(containern), dimension(:), allocatable :: nton


! load ramp model in ascii vtk
   call load_model(amesh, velocity, theo_time, branch_id)

! find source node index from coordinates
   k = find_node_from_xy(amesh, 500._pr, 500._pr, 1.0e-6_pr)
   write(*,*) 'source node index = ', k-1

! fast option off
   adiff%fast = .false.

! adding diffraction points: D1 and D2
adiff%NdiffNodes = 2
allocate(adiff%nodes(adiff%NdiffNodes))

adiff%nodes(1) = find_node_from_xy(amesh, 3333.3_pr, 1666.7_pr, 1.0e-6_pr)
adiff%nodes(2) = find_node_from_xy(amesh, 6666.7_pr, 2254.42_pr, 1.0e-6_pr)

write(*,*) 'diffraction D1   = ', adiff%nodes(1)-1
write(*,*) 'diffraction D2   = ', adiff%nodes(2)-1

   write(0,*) 'starting time computing'
   call cpu_time(start_time)
   call pre_timeonevsall2d_onvertex(amesh, k, traveltime, nton)
   call timeonevsall2d(amesh, velocity, traveltime, nton, adiff)
   call cpu_time(finish_time)
   write(*,*) 'cpu time for timeonevsall2d : ', finish_time - start_time

! relative error in percent with respect to the theoretical solution
   allocate(error_time(amesh%Nnodes))
   do i = 1, amesh%Nnodes
      if (i == k) then
         error_time(i) = 0._pr
      else
         error_time(i) = 100._pr * (traveltime(i) - theo_time(i)) / theo_time(i)
      endif
   enddo

! convert branch_id to real for vtk dump routine
   allocate(branch_id_r(amesh%Nnodes))
   do i = 1, amesh%Nnodes
      branch_id_r(i) = real(branch_id(i), pr)
   enddo

! free nton
   call free_nton(nton)

! dump result in ascii VTK
   write(*,*) 'dumping time in result.vtk'
   open(10, file='result.vtk', form='formatted')
   call dumpmeshvtk(10, amesh)
   call dumpcellattributevtk(10, amesh, velocity,    'velocity',   .true.)
   call dumpnodeattributevtk(10, amesh, traveltime,  'time',       .true.)
   call dumpnodeattributevtk(10, amesh, theo_time,   'theo_time',  .false.)
   call dumpnodeattributevtk(10, amesh, error_time,  'error_time', .false.)
   call dumpnodeattributevtk(10, amesh, branch_id_r, 'branch_id',  .false.)
   close(10)

contains
!###############################################################################
subroutine load_model(amesh, velocity, theo_time, branch_id)
! load the ramp vtk file called input_velocity.vtk
! expected:
!   - mesh
!   - CELL_DATA: velocity
!   - POINT_DATA: at least branch_id and theo_time (order can vary)

use generic
use LAT_mesh
implicit none

type(mesh) :: amesh
real(pr),    dimension(:), allocatable :: velocity
real(pr),    dimension(:), allocatable :: theo_time
integer(pin), dimension(:), allocatable :: branch_id

integer :: i, j, idum, cell_list_size, ios
integer(pin) :: npoint_data
character(len=64) :: keyword, datatype, scalar_name, lookup_word, lookup_name
logical :: got_branch, got_theo

!----------------------------------------------------------
! mesh
!----------------------------------------------------------
  open(12, file="input_velocity_complex_branch_id.vtk", status="old", action="read")

! VTK header
  do i = 1, 4
     read(12,*)
  enddo

! POINTS
  read(12,*) keyword, amesh%Nnodes, datatype
  allocate(amesh%px(amesh%Nnodes), amesh%py(amesh%Nnodes), amesh%pz(amesh%Nnodes))
  do i = 1, amesh%Nnodes
     read(12,*) amesh%px(i), amesh%py(i), amesh%pz(i)
  enddo

! POLYGONS
  read(12,*) keyword, amesh%Ncells, cell_list_size
  allocate(amesh%cell(amesh%Ncells, 3))
  do i = 1, amesh%Ncells
     read(12,*) idum, (amesh%cell(i,j), j=1,3)
  enddo

! vtk files are 0-based
  amesh%cell = amesh%cell + 1

!----------------------------------------------------------
! CELL_DATA -> velocity
!----------------------------------------------------------
! blank line
  read(12,*)
! CELL_DATA header
  read(12,*)
! SCALARS line
  read(12,*)
! LOOKUP_TABLE line
  read(12,*)

  allocate(velocity(amesh%Ncells))
  do i = 1, amesh%Ncells
     read(12,*) velocity(i)
  enddo

!----------------------------------------------------------
! POINT_DATA -> scalars
!----------------------------------------------------------
! blank line
  read(12,*)
! POINT_DATA N
  read(12,*) keyword, npoint_data

  allocate(theo_time(amesh%Nnodes))
  allocate(branch_id(amesh%Nnodes))
  theo_time = 0._pr
  branch_id = 0

  got_branch = .false.
  got_theo   = .false.

! Read scalar blocks until EOF
  do
     read(12,*,iostat=ios) keyword, scalar_name, datatype, idum
     if (ios /= 0) exit

! next line should be LOOKUP_TABLE default
     read(12,*) lookup_word, lookup_name

     if (trim(scalar_name) == 'branch_id') then
        do i = 1, amesh%Nnodes
           read(12,*) branch_id(i)
        enddo
        got_branch = .true.

     elseif (trim(scalar_name) == 'theo_time' .or. trim(scalar_name) == 'traveltime') then
        do i = 1, amesh%Nnodes
           read(12,*) theo_time(i)
        enddo
        got_theo = .true.

     else
! unknown point scalar: skip it
        do i = 1, amesh%Nnodes
           read(12,*)
        enddo
     endif
  enddo

  close(12)

  if (.not. got_branch) then
     stop 'load_model: branch_id not found in input_velocity.vtk'
  endif

  if (.not. got_theo) then
     write(*,*) 'warning: theo_time not found in input_velocity.vtk; set to zero'
  endif

  return
end subroutine load_model
!###############################################################################
function find_node_from_xy(amesh, xs, ys, tol) result(k)
use generic
use LAT_mesh
implicit none

type(mesh), intent(in) :: amesh
real(pr), intent(in) :: xs, ys, tol
integer(pin) :: k

integer(pin) :: i, nfound
real(pr) :: d2, best_d2

k = 0
nfound = 0
best_d2 = huge(1._pr)

do i = 1, amesh%Nnodes
   d2 = (amesh%px(i)-xs)**2._pr + (amesh%py(i)-ys)**2._pr
   if (d2 <= tol**2) then
      nfound = nfound + 1
      if (d2 < best_d2) then
         best_d2 = d2
         k = i
      endif
   endif
enddo

if (nfound == 0) then
   write(*,*) 'ERROR: source node not found at coordinates ', xs, ys
   stop
elseif (nfound > 1) then
   write(*,*) 'WARNING: multiple nodes found near source, using closest one'
endif

end function find_node_from_xy
end program ramp
